import { Module } from '../../Module';
import { NextHook } from '../../types';
import { IInstance } from '../../types/IInstance';
export declare class FreeWheelExtension extends Module {
    name: string;
    private sdk;
    private mediaElement;
    private adManager;
    private adContext;
    private adsRequested;
    private adBreaks;
    private currentAdBreak;
    private currentAd;
    private adSequenceIndex;
    private adContainer;
    private prevCurrentTime;
    constructor(instance: IInstance);
    onControllerPlay(next: NextHook): void;
    onControllerPause(next: NextHook): void;
    onControllerSetVolume(next: NextHook, volume: number): void;
    onControllerSeekTo(next: NextHook): void;
    createMediaElement(): void;
    private onInstanceInitialized;
    onAdRequestComplete(event: any): void;
    adClick(): void;
    private onSlotStarted;
    private onSlotEnded;
    private onAdImpression;
    private onAdImpressionEnd;
    private onPlayerTimeUpdate;
    private onPlayerEnded;
    private slotToAdBreak;
    private playAdBreak;
    private shouldSkipPreroll;
}
